{% set version = "2.12.1" %}
{% set so_name = "6.18.3" %}
{% set so_name_major = so_name.split('.')[0] %}

package:
  name: freetype-split
  version: {{ version }}

source:
  url: https://download.savannah.gnu.org/releases/freetype/freetype-{{ version }}.tar.gz
  sha256: efe71fd4b8246f1b0b1b9bfca13cfff1c9ad85930340c27df469733bbb620938
  patches:
    - CVE-2022-37434.patch

build:
  number: 3
  run_exports:
    # has removed symbols at minor versions, but only very rarely.  Go with major.
    #  https://abi-laboratory.pro/tracker/timeline/freetype/
    - {{ pin_subpackage('freetype') }}

requirements:
  build:
    - libtool  # [unix]
    - {{ compiler('c') }}
    - cmake  # [win]
    - make  # [not win]
    - ninja  # [win]
  host:
    - libpng
    - zlib

outputs:

  # Everything needed to build against libfreetype (scripts in bin are for build config)
  - name: freetype
    script: install.py
    build:
      run_exports:
        - {{ pin_subpackage('libfreetype' ~ so_name_major) }}
    requirements:
      host:
        - {{ pin_subpackage('libfreetype' ~ so_name_major, exact=True) }}        # [unix]
      run:
        - {{ pin_subpackage('libfreetype' ~ so_name_major, exact=True) }}        # [unix]
    test:
      commands:
        - ${PREFIX}/bin/freetype-config --version  # [not win]
      # Need these things
        - test -f ${PREFIX}/lib/libfreetype{{ SHLIB_EXT }}                       # [unix]
        - test -f ${PREFIX}/lib/libfreetype.{{ so_name_major }}{{ SHLIB_EXT }}   # [osx]
        - test -f ${PREFIX}/lib/libfreetype{{ SHLIB_EXT }}.{{ so_name_major }}   # [linux]
        - test -f ${PREFIX}/lib/libfreetype{{ SHLIB_EXT }}.{{ so_name }}         # [linux]
        - if not exist %PREFIX%\\Library\\lib\\freetype.lib exit 1               # [win]
        - test -f ${PREFIX}/include/freetype2/freetype/freetype.h                             # [unix]
        - if not exist %PREFIX%\\Library\\include\\freetype2\\freetype\\freetype.h exit 1      # [win]
        - test -f ${PREFIX}/lib/pkgconfig/freetype2.pc                            # [unix]
        - if not exist %PREFIX%\\Library\\lib\\pkgconfig\\freetype2.pc exit 1     # [win]
        - if not exist %PREFIX%\\Library\\lib\\cmake\\freetype\\freetype-config.cmake exit 1     # [win]
        - test -f ${PREFIX}/bin/freetype-config                               # [unix]
      # Exclude these things
        - test ! -f ${PREFIX}/lib/libfreetype.a                               # [unix]
        - if exist %PREFIX%\\Library\\bin\\freetype.dll exit 1                # [win]

  # Only what's needed for run_exports downstream
  - name: libfreetype{{ so_name_major }}
    script: install.py
    build:
      run_exports:
        - {{ pin_subpackage('libfreetype' ~ so_name_major) }}
    requirements:
      build:
        - {{ compiler('c') }}
      host:
        - libpng
        - zlib
      run:
        - {{ pin_subpackage('_libfreetype_api', max_pin='x.x.x') }}              # [win]
    test:
      commands:
      # Need these things
        - test -f ${PREFIX}/lib/libfreetype.{{ so_name_major }}{{ SHLIB_EXT }}   # [osx]
        - test -f ${PREFIX}/lib/libfreetype{{ SHLIB_EXT }}.{{ so_name_major }}   # [linux]
        - test -f ${PREFIX}/lib/libfreetype{{ SHLIB_EXT }}.{{ so_name }}         # [linux]
        - if not exist %PREFIX%\\Library\\bin\\freetype.dll exit 1               # [win]

  # Clobber preventer for Windows; prevents multiple freetype.dll files from being
  # installed simultaneously. This lets us avoid exporting a strict pin on the
  # libfreetype API which is not strictly correlated with the ABI.
  - name: _libfreetype_api
    build:
      skip: true  # [not win]
    about:
      summary: >
        An empty package that prevents multiple ABIs of libdavid being installed simultaneously on Windows.

about:
  home: https://www.freetype.org/
  license: GPL-2.0-only OR FTL
  license_file:
    - docs/GPLv2.TXT
    - docs/FTL.TXT
  summary: A Free, High-Quality, and Portable Font Engine
  description: |
    FreeType is designed to be small, efficient, highly customizable
    and portable while capable of producing high-quality output (glyph images)
    of most vector and bitmap font formats.
  doc_url: http://freetype.sourceforge.net/freetype2/documentation.html
  doc_source_url: https://sourceforge.net/projects/freetype/?source=navbar
  dev_url: http://git.savannah.gnu.org/cgit/freetype/

extra:
  recipe-maintainers:
    - ccordoba12
    - msarahan
    - ocefpaf
